---
title: "MiniProject2"
author: "Yingqi Zheng"
date: "10/23/2017"
output: html_document
---

```{r}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

Library packages
```{R, Message = FALSE}
library(ggplot2)
library(tidyverse)
data(candidates)
```

```{R}
candyear <- candidates %>%
  select(-cand_office_district, -cand_ici, -cand_status, -cand_pcc, -cand_st1, -cand_st2, -cand_city, -cand_state, -cand_zip) %>%
  filter(cand_election_yr == 2012) %>%
  filter(cand_party_affiliation %in% c("DEM", "REP")) %>%
  filter(cand_office == "S")
```


```{r}
candMA <- candyear %>%
  filter(cand_office_state == "MA")
```

```{r}
contritidy <- contributions %>%
  select(cmte_id, name, state, cand_id)

contricand <-candyear %>%
  right_join(contritidy, by = "cand_id") %>%
  filter(cand_office == "S") %>%
  filter(!is.na(cand_name)) %>%
  arrange(cand_office_state)
```

```{R}
party <- contricand %>%
  group_by(cand_office_state, cand_party_affiliation) %>%
  summarise(nparty = sum(n())) %>%
  spread(key = cand_party_affiliation, value = nparty)
```


```{R}
party[is.na(party)] <- 0

party2 <- party %>%
  mutate (DEMtoREP = DEM/REP)

```

```{r}
candplot <- ggplot(data = party2, aes(x = cand_office_state, y = DEMtoREP)) + geom_point() + scale_y_sqrt()
candplot
```

```{r}
party3 <- party2 %>%
  filter(!cand_office_state == "DE")

candplot2 <- ggplot(data = party3, aes(x = cand_office_state, y = DEMtoREP), alpha = 0.2) + 
  geom_point() + 
  scale_y_sqrt() + 
  geom_hline(yintercept = 1) +  
  geom_text(aes(0,1,label = 'ratio=1', hjust = -.3, vjust = -0.5)) +
  labs(title = "Money Received by Democrat VS Republican in Each State") +
  ylab(label = "Ratio of Money Received by Democrat VS Republican") +
  theme(plot.title = element_text(hjust = 0.5))
candplot2
```

